### ISSUE TITLE
Always notifying that file needs documentation headers

### ISSUE THREAD

**Issue by echoix** [d1820/CodeDocumentor#14]
It's a nice feature that was added that suggests to add documentation for the whole file, however, since it was added, all the files always have a "message" CD1607 that the file needs documentation headers, even if it doesn't, and even if the fix doesn't add any output. I have the setting of "public members only" activated. And there are some partial classes since I'm using the MVVM Community Toolkit.

**Comment by d1820** [comment]
Fixed in #15
