### ISSUE TITLE
Background Process Threads not showing individual comment context menu

### ISSUE THREAD

**Issue by d1820** [d1820/CodeDocumentor#22]
[echoix](https://github.com/echoix) commented [3 days ago](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1548244142) • 
Could it be a different suggestion to only add missing instead of overwriting all the manually tuned strings?
For example, I usually use the suggestion to add documentation everywhere and improve when needed. Later on, I add new stuff and want to add what's missing. Since I don't have a code fix suggestion that would add documentation on a single method or property (that isn't en empty summary or empty method argument suggestion), I need to preview the changes, copy from the preview the suggestions that I want to use, then paste them manually.

Or, if it could be possible in the preview to use checkboxes to select what updates to include, that could be another solution.

@d1820
Owner
[d1820](https://github.com/d1820) commented [3 days ago](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1548256813)
@echoix so based on what you're saying are you constantly just rerunning the document whole file instead of just running individual methods you want to update or add documentation to? there should be two different selections available either document whole file, or document an individual method or property

@[echoix](https://github.com/echoix)
echoix commented [3 days ago](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1548273290)
I'm not sure what config changed in the last few weeks, but I don't have a valid suggestion for only one property or method. Maybe there is a conflict between extensions too...

Screenshots
@d1820
Owner
[d1820](https://github.com/d1820) commented [3 days ago](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1548288140)
@echoix others have seen this issue and it ended up being related to needing to upgrade visual studio it appears they released an interim version that has broken some extension functionalities upgrading to the latest version of VS fixed to those issues. are you on the latest version or can you confirm what version you are on please?

@[echoix](https://github.com/echoix)
echoix commented [3 days ago](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1548289324)
I'm pretty up to date, on all extensions too, I'm on VS 2022 17.5.5

@[echoix](https://github.com/echoix)
echoix commented [yesterday](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1551321513)
I found it! CPU usage was always high, and I was getting tired of hearing my fan. I looked up and one of the suggestions is to uncheck pull diagnostics and uncheck "Run code analysis in separate process".

"Run code analysis in separate process" was checked like this:
[image
](https://user-images.githubusercontent.com/27212526/238950346-52692252-c0f4-49bc-817d-a4b805c9e90f.png)

And if I uncheck "Run code analysis in separate process", suggestions for a single field or property works correctly!
[image
](https://user-images.githubusercontent.com/27212526/238950448-514b01e7-02bc-401d-a7a0-8c420bbb83ea.png)

I retried toggling on "Run code analysis in separate process", restarting Visual Studio, confirmed that the suggestions don't work, then unchecking again, restart VS, then the suggestions work.
And this was now with VS 2022 17.6, out yesterday.

@d1820
Owner
[d1820](https://github.com/d1820) commented [yesterday](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1551476426)
wow.. hahah. I'll convert this flow to a bug and log it to take a look at

@[echoix](https://github.com/echoix)
echoix commented [yesterday](https://github.com/d1820/CodeDocumentor/pull/20#issuecomment-1551529114)
wow.. hahah. I'll convert this flow to a bug and log it to take a look at

It's probably the way that extensions will be in the future, Out-Of-Process, just like the new WinForms designer. To decouple from having the IDE load an assembly, and can't unload it and once loaded, only that specific version is available for everything.

**Comment by d1820** [comment]
@echoix I have background enabled and all works fine.. One difference I do notice though is for your background service you have entire solution whereas I run it as current document and then for a show compiler errors I use open documents and you use solution that could be the problem could you try re-enabling your run code analysis and separate process but switching those dropdowns at the top to what I outlined above

**Comment by d1820** [comment]
Closing due to lack of response

**Comment by d1820** [comment]
I see the way the code analysis settings are displayed have changed.. i will look into this

**Comment by bcssov** [comment]
Hi just discovered this VSIX. I like it. I do prefer to use stuff with "use in separate process options" toggled on. What struck me as odd when you mentioned that analyzers are broken, while I have another extension which shows up just fine. It generates JSONAttribute properties for me.

I did some digging for a start and calling DI in GetRule settings is a part of the problem. Even if I hardcode values in OptionsService it completely fails to register. 

I then attempted switching to a mock of DIContainer (ConcurrentDictionary) and that as well failed. Only by hardcoding the options and the optionservice instance did I manage to get the options to show.

**Comment by d1820** [comment]
> Hi just discovered this VSIX. I like it. I do prefer to use stuff with "use in separate process options" toggled on. What struck me as odd when you mentioned that analyzers are broken, while I have another extension which shows up just fine. It generates JSONAttribute properties for me.
> 
> I did some digging for a start and calling DI in GetRule settings is a part of the problem. Even if I hardcode values in OptionsService it completely fails to register.
> 
> I then attempted switching to a mock of DIContainer (ConcurrentDictionary) and that as well failed. Only by hardcoding the options and the optionservice instance did I manage to get the options to show.


@bcssov 
I notice something different. I see all the DI working and loading(I have refactored this) but what the issue seems to look like to me is in the background process VS is not calling any of the analyzer Initialize ```public override void Initialize(AnalysisContext context)``` All the SupportedDiagnostics events fire and the optionsService loads and has all the correct settings. That is why i feel like its a bug in VS cause what ever they did to run it all in background for some reason Initialize is not called. Soon as i remove "background" setting the initialize is called on main thread correctly. In your when you debug it in background status do you see your Initialize methods called?

**Comment by d1820** [comment]
I have an update coming version 2.0.2.X that seemingly gets this working on the background thread, but you need to deselect "Run code analysis on latest .NET" and I also needed to change the **Run background code analysis for** to Entire Solution. Hoping to have this released by EOD 2/14/2024

**Comment by bcssov** [comment]
> > Hi just discovered this VSIX. I like it. I do prefer to use stuff with "use in separate process options" toggled on. What struck me as odd when you mentioned that analyzers are broken, while I have another extension which shows up just fine. It generates JSONAttribute properties for me.
> > I did some digging for a start and calling DI in GetRule settings is a part of the problem. Even if I hardcode values in OptionsService it completely fails to register.
> > I then attempted switching to a mock of DIContainer (ConcurrentDictionary) and that as well failed. Only by hardcoding the options and the optionservice instance did I manage to get the options to show.
> 
> @bcssov I notice something different. I see all the DI working and loading(I have refactored this) but what the issue seems to look like to me is in the background process VS is not calling any of the analyzer Initialize `public override void Initialize(AnalysisContext context)` All the SupportedDiagnostics events fire and the optionsService loads and has all the correct settings. That is why i feel like its a bug in VS cause what ever they did to run it all in background for some reason Initialize is not called. Soon as i remove "background" setting the initialize is called on main thread correctly. In your when you debug it in background status do you see your Initialize methods called?

You could say I didn't need to test when I converted all into static variables and didn't initialize DI or even create optionsservice in there manually I got the whole extension to work, albeit with hardcoded settings.

I am looking forward to the next release. One thing that did cause problems where I had to end up disabling the extension in that state is that VS would lockup for me with all the analyzers (and there aren't that many of them). Shutting down VS and restarting reported problems with the extension performance. I don't believe the official version will have such problems given what you've mentioned.
