### ISSUE TITLE
Support file scoped namespace

### ISSUE THREAD

**Issue by bdongus** [d1820/CodeDocumentor#23]
Currently the code documentor doesn't work on source files using a file scoped namespace.
Example:
```cs
namespace MyNamespace; 
public class Class1 {

}
```

**Comment by d1820** [comment]
The extension already support this. looks like MS has broken something in the 17.6.X release flow. I verified the extension on early versions and it handled that fine. I get errors on wpf tooling unhandled exceptions that are part of the VS2022. I would wait for the next MS update cause from what i see its nothing related to the extension
