### ISSUE TITLE
Cannot see wave line below the member function

### ISSUE THREAD

**Issue by harry-chin** [d1820/CodeDocumentor#25]
After installing, I have checked the insturction, but I cannot add a document for single function as there is no wave line below function name and cannot see bulb due to this either. 

I am using vs2022 17.6.6

**Comment by d1820** [comment]
can you cross check you settings for code analysis based on this thread https://github.com/d1820/CodeDocumentor/issues/22#issuecomment-1553412776

**Comment by harry-chin** [comment]
After uncheck the item and restart vs2022, it works!
Thanks!
