### ISSUE TITLE
Shows "XXX must have a documentation header" on private members.

### ISSUE THREAD

**Issue by CheloXL** [d1820/CodeDocumentor#3]
I have setup the "Enable comments for public members only" option to true, but I'm still getting the above error on every internal/private class/method/property.

I have on a solution root level `<GenerateDocumentationFile>True</GenerateDocumentationFile>` on my `Directory.Build.props` (not sure if that can affect how CD works).

I would expect, with the above option setup in true, to not be notified about any missing documentation on any non public/protected members/classes.

**Comment by d1820** [comment]
This has been resolved with version 1.1.3. When toggling the setting Visual Studio will need to be restarted for it to take affect. This is due to when the analyzers are loaded into the shell.
