### ISSUE TITLE
After update for ReSharper 2024.1, No longer seeing the menu item for documenting code

### ISSUE THREAD

**Issue by VelvetAndrea** [d1820/CodeDocumentor#33]
After update for ReSharper 2024.1, I'm no longer seeing the menu item for documenting code.

The tool Tip is missing the link:
![LinkMissingInToolTip](https://github.com/d1820/CodeDocumentor/assets/166546354/67f271a2-bc00-449f-b301-d8786df8edd2)

And in Crtl+.
![LinkMissingInCtrlDot](https://github.com/d1820/CodeDocumentor/assets/166546354/e263a027-f85f-4c98-a2ed-bb4b5054795a)

Additionally, When I suspend ReSharper, the functionality works as advertised.  I'm thinking the hook into ReSharper changed in this version, or they are blocking additions to the menus unless it is a ReSharper extension.  Just guesses here.

Thanks!
Andrea

**Comment by d1820** [comment]
Sounds like Resharper is interfering with Visual Studio context menus. Have you tried

https://resharper-support.jetbrains.com/hc/en-us/articles/206546519-There-are-no-Visual-Studio-items-in-context-menu
```
E.g. Surround With, Insert Snippets, Organize Usings.

Solution:

Untick "Hide overridden VS menu items" in ReSharper | Options | Environment | Keyboard & Menus. 
```

or 

```
Resharper hiding context menu visual studio
To add ReSharper options back to the context menu in Visual Studio, follow these steps:

Go to “Tools” > “Customize…”.
In the “Toolbars” tab, tick “Context Menus”.
Find “Other Context Menus” > “Easy MDI Document Window”.
Switch to the “Commands” tab.
Search for “ReSharper” and locate “ReSharper_LocateInSolutionExplorerAction”.
Drag it into the menu.
Click “Close”.
If you’re missing refactor options in the context menu, try turning on the “Merge Visual Studio Light Bulb actions into ReSharper bulb” option in ReSharper | Options | Code Inspection | Settings.

If you’re experiencing missing commands like “Refactor” or “Organize Usings”, try unchecking “Hide overridden Visual Studio Menu items” in “Environment” > “Keyboard & Menus” > “Menus & Toolbars”.

Remember, ReSharper may override some Visual Studio commands, but it often provides better alternatives.
```

**Comment by VelvetAndrea** [comment]
I tried going through those, but I am unable to find these particular settings in ReSharper.  Evidently, they have changed where settings are located and I can't find them.

**Comment by VelvetAndrea** [comment]
I have turned in a bug to ReSharper.  They shouldn't be blocking additions from other extensions.  For now, my workaround will be that I have to suspend ReSharper to work on the documentation.  Annoying, but there it is.

**Comment by VelvetAndrea** [comment]
OH, I was reading about the error logging and I looked at the log and found this:

CodeDocumentor: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at CodeDocumentor.Analyzers.BaseAnalyzerSettings.<>c__DisplayClass1_0.<LookupSeverity>b__0()
   at CodeDocumentor.Helper.TryHelper.Try[TResult](Func`1 action, Func`2 exceptionCallback, Boolean reThrow, Int32 eventId, Int16 category) in D:\a\CodeDocumentor\CodeDocumentor\CodeDocumentor\Helper\TryHelper.cs:line 29

**Comment by VelvetAndrea** [comment]
CoPilot found the setting for Version 2024.1 in ReSharper.  I should have consulted it earlier.

![image](https://github.com/d1820/CodeDocumentor/assets/166546354/18ec84bb-69b0-4326-aeae-ea463f2bb0a0)


I change from "Hide from Visual Studio Indicator to the following.
![ReSharperChanges](https://github.com/d1820/CodeDocumentor/assets/166546354/b28302dd-f22e-4d45-b824-79b002d64e47)

Thanks,
Andrea
