### ISSUE TITLE
Adding comments across entire project / solution

### ISSUE THREAD

**Issue by greyghostbrewery** [d1820/CodeDocumentor#34]
How do you run the tool across an entire project or solution?

**Comment by d1820** [comment]
Here is a demo

Steps:

1. open a file
2. right click on a method or class that does not have any comments
3. select "Documentor this whole file"
4. select "solution" at the bottom of the preview window
5. select apply

![commentAll](https://github.com/d1820/CodeDocumentor/assets/377631/96f2635e-1e98-4fff-ac5a-de010748aa0d)
